import type { Metadata } from "next";
import { Geist, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import { ThemeProvider } from "@/components/theme-provider";
import { accents, themes } from "@/config/theme";
import {
	DEFAULT_ACCENT,
	DEFAULT_THEME,
	STORAGE_ACCENT_KEY,
	STORAGE_THEME_KEY,
} from "@/config/theme-storage";
import { Inter, Mono, spaceGrotesk } from "@/libs/fonts";
import { cn } from "@/utils/cn";

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const themeBootScript = `
(() => {
	const themeKey = ${JSON.stringify(STORAGE_THEME_KEY)};
	const accentKey = ${JSON.stringify(STORAGE_ACCENT_KEY)};
	const fallbackTheme = ${JSON.stringify(DEFAULT_THEME)};
	const fallbackAccent = ${JSON.stringify(DEFAULT_ACCENT)};
	const validThemes = new Set(${JSON.stringify([...themes])});
	const validAccents = new Set(${JSON.stringify(accents.map((accent) => accent.name))});

	try {
		const root = document.documentElement;
		const storedTheme = window.localStorage.getItem(themeKey);
		const storedAccent = window.localStorage.getItem(accentKey);
		root.dataset.theme = validThemes.has(storedTheme) ? storedTheme : fallbackTheme;
		root.dataset.accent = validAccents.has(storedAccent) ? storedAccent : fallbackAccent;
		root.dataset.themeReady = "true";
	} catch {
		document.documentElement.dataset.themeReady = "true";
	}
})();
`;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			data-theme="macchiato"
			data-accent="peach"
			data-theme-ready="false"
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				Mono.variable,
				Inter.variable,
				spaceGrotesk.variable,
				"font-mono",
				jetbrainsMono.variable,
			)}
		>
			<head>
				<script
					dangerouslySetInnerHTML={{ __html: themeBootScript }}
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
				/>
			</head>
			<body className="min-h-full flex flex-col">
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	);
}
